"""к ассетам добавлены вычисляемые функции

Revision ID: 569ddb5f7ea5
Revises: bbd8e0e7fa04
Create Date: 2026-09-26 10:27:07.139612+00:00

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569ddb5f7ea5'
down_revision: Union[str, Sequence[str], None] = 'bbd8e0e7fa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('color_histogram', Vector(96), nullable=True))
    op.add_column('assets', sa.Column('phash', sa.String(length=16), nullable=True))
    op.add_column('assets', sa.Column('avg_color_rgb', sa.String(length=7), nullable=True))
    op.add_column('assets', sa.Column('brightness', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('contrast', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('aspect_ratio', sa.Float(), nullable=True))
    op.create_index(op.f('ix_assets_phash'), 'assets', ['phash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_phash'), table_name='assets')
    op.drop_column('assets', 'aspect_ratio')
    op.drop_column('assets', 'contrast')
    op.drop_column('assets', 'brightness')
    op.drop_column('assets', 'avg_color_rgb')
    op.drop_column('assets', 'phash')
    op.drop_column('assets', 'color_histogram')
    # ### end Alembic commands ###
